### ISSUE TITLE
Is nomination of data sources an existing feature?

### ISSUE THREAD

**Issue by waldoj** [centerforgov/open-data-portal-requirements#3]
Under "Community Features," [the "Customers" requirement specifies](https://github.com/centerforgov/open-data-portal-requirements#customers-3):

> must be able to nominate data resources for public release

Is this a standard feature in Socrata, CKAN, Junar, ArcGIS Open Data, DKAN, or OpenDataSoft? I haven't noticed it in any of those, but I also haven't looked for it. And if it isn't, how do you feel about establishing a _must_-level requirement for a feature that doesn't yet exist in open data repositories? (There's no judgment in that question—I could argue either side of that.)

**Comment by technickle** [comment]
Some open data solutions directly support this requirement. But the implementation could be as simple as a link to a web form which sends an email to an administrator.  I supposed accepting dataset suggestions is also a policy decision. Do you think this requirement should be switched from "must" to "may"?

**Comment by sidburgess** [comment]
Would providing an email address to the portal administrator satisfy this? (rather than a webform or a link to a webform)

**Comment by waldoj** [comment]
It sounds like this isn't really a feature of the software, then—it sounds like this is an administrative process that you want to exist, which could have a vector of any feedback mechanism at all.

**Comment by technickle** [comment]
I'll switch the requirement to "may"

**Comment by jqnatividad** [comment]
I know this issue is already closed, but FWIW, CKAN does have an extension to support this.
https://github.com/conwetlab/ckanext-datarequests and can be seen in action here
http://data.beta.nyc/datarequest

In terms of citizen engagement, I think it should be encouraged and promoted.  Perhaps, a best practice to include in the [Open Data: Getting Started Guide](https://www.gitbook.com/book/centerforgov/open-data-getting-started/details)?

Note how it gives a not too subtle signal to the publisher as it tracks the turnaround time of the request.  And all the request data is available thru the datarequest API.
